name: Resume

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build Resume
      run: docker buildx build . --file Dockerfile --target resume --output ./build --build-arg OUTNAME=resume
    - name: Publish Resume
      uses: actions/upload-artifact@v3
      with:
        name: resume
        path: ./build/resume.pdf
